### ISSUE TITLE
Implement upgrade that increases resource trickle rate

### ISSUE THREAD

**Issue by andy5995** [0ad-matters/no-gather#3]
https://github.com/0ad-matters/no-gather/blob/1637662bfddef6381a49e19478f3801557531144/simulation/components/GuiInterface.js#L42-L48

The rate at which resources accumulate should be based on game time and game speed. The exact values I'm not sure of yet but to start with I'm thinking that every 5 Seconds a player gets five units of each resource. After 10 minutes of game time that increases to eight units of each resources. The values should be multiplied by the game speed.

@LangLangBart do you have any interest in working on this? Or have suggestions about the values, or method of implementation?

**Comment by andy5995** [comment]
~TwainRick suggested making it so you could rebalance with resources accumulate, like is done with traders.~

I misunderstood. He said the rate of accumulation seems fine so far. (After one test game)

**Comment by andy5995** [comment]
Implementing it differently will probably be a requirement. see https://github.com/0ad-matters/no-gather/issues/5

**Comment by livvv2k** [comment]
The game speed / game time part of this now fixed as cmpTimer is based on sim time. x20 would tick 5 seconds 20x faster and so on.

Having the trickle be variant could be done via adding a sigmoid function which grows with t Time I guess.

**Comment by andy5995** [comment]
The implementation was vastly improved by @livvv2k in https://github.com/0ad-matters/no-gather/commit/a7ddc31e81fc318d69fc92adf1d479069ba4f60f and I made some adjustments in https://github.com/0ad-matters/no-gather/commit/03126dcfde05e6bc1d5421076e32ff27799e8dd5

What's needed now is implementing a couple upgrades that increases the trickle rate. Or maybe even better, add the upgrade to the town and city phase upgrades. Anyone know how to do that or want to submit a PR?

**Comment by andy5995** [comment]
> What's needed now is implementing a couple upgrades that increases the trickle rate. Or maybe even better, add the upgrade to the town and city phase upgrades. Anyone know how to do that or want to submit a PR?

I found the answer in technologies/subterranean_aqueducts.json

**Comment by andy5995** [comment]
> The game speed / game time part of this now fixed as cmpTimer is based on sim time. x20 would tick 5 seconds 20x faster and so on.
> 
> Having the trickle be variant could be done via adding a sigmoid function which grows with t Time I guess.

@livvv2k I didn't see your comment until just now... Thanks for the suggestion. I'll keep it as is for now and maybe make changes after some play-testing.
